/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vova' at '2/19/17 11:16 PM' with Gradle 3.1
 *
 * @author vova, @date 2/19/17 11:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
