import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'vova' at '2/19/17 11:16 PM' with Gradle 3.1
 *
 * @author vova, @date 2/19/17 11:16 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Object classUnderTest = new Object();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
